define({
  root: {
    addLayer: "Add Layer",
    layerName: "Layer",
    layerRefresh: "Refresh",
    layerLabel: "Label",
    upload: "Image",
    actions: "Actions",
    popupOk: "OK",
    popupCancel: "Cancel",
    mainPanelTextPlaceholder: "ex: HIGHWAY CONDITIONS",
    invalidInterval: "Only numeric characters supported.",
    uploadImage: "Upload Image",
    iconColumnText: "Icon",
    labelColumnText: "Display Name",
    refreshInterval: "1 'Evaluated as time in Minutes'",
    refreshIntervalTitle: "Evaluated as time in Minutes",
    noLayers: "No feature layers are available",
    mainPanelText: "Main Panel Text",
    mainPanelIcon: "Main Panel Image",
    refreshIntervalInstruction: "Refresh Interval",
    optionsText: "Options",
    symbolOptionsText: "Symbol Options",
    iconOptionsText: "Icon Options",
    sympolPopupTitle: "Set Symbol",
    rdoLayerTitle: "Set Symbol",
    rdoLayer: "Layer Symbol",
    rdoCustom: "Custom Symbol",
    chkCluster: "Enable Clustering",
    defineClusterSymbol: "Cluster Symbol",
    defineThemeClusterSymbol: "Cluster Symbol from Theme",
    rdoEsri: "Esri Symbol",
    rdoLayerIcon: "Use Symbol as Icon",
    rdoCustomIcon: "Upload Custom Icon",
    editCustomSymbol: "Edit Custom Symbol",
    editCustomIcon: "Edit Custom Icon",
    missingRefreshValue: "Please provide a refresh interval value."
  },
  "ar": false,
  "cs": false,
  "da": false,
  "de": false,
  "es": false,
  "et": false,
  "fi": false,
  "fr": false,
  "he": false,
  "it": false,
  "ja": false,
  "ko": false,
  "lt": false,
  "lv": false,
  "nb": false,
  "nl": false,
  "pl": false,
  "pt-BR": false,
  "pt-PT": false,
  "ro": false,
  "ru": false,
  "sv": false,
  "th": false,
  "tr": false,
  "zh-cn": false
});
