define({
  root: {
    addLayer: "Add Layer",
    layerName: "Layer",
    layerRefresh: "Refresh",
    layerLabel: "Label",
    upload: "Image",
    actions: "Actions",
    filter: "Filter",
    filterBtnTitle: "Edit Query Filter",
    noFilterTip: "No filters defined",
    filterPopupTitle: "Add Query Filter",
    popupOk: "OK",
    popupCancel: "Cancel",
    filterInvalid: "Invalid Query Filter",
    invalidUrlTip: "The URL you have entered is invalid or inaccessible.",
    urlPopupTitle: "Add Feature Service URL",
    mainPanelTextPlaceholder: "ex: HIGHWAY CONDITIONS",
    invalidInterval: "Only numeric characters supported.",
    useColumnText: "Use",
    uploadImage: "Upload Image",
    iconColumnText: "Icon",
    labelColumnText: "Display Name",
    refreshInterval: "5 'Evaluated as time in Minutes'",
    noLayers: "No feature layers are available",
    mainPanelText: "Main Panel Text",
    mainPanelIcon: "Main Panel Image",
    refreshIntervalInstruction: "Refresh Interval",
    downloadRefreshConfig: "Download Config",
    downloadRefreshScript: "Download Script",
    optionsText: "Options",
    symbolOptionsText: "Symbol Options",
    iconOptionsText: "Icon Options",
    sympolPopupTitle: "Set Symbol",
    rdoLayerTitle: "Set Symbol",
    rdoLayer: "Layer Symbol",
    rdoCustom: "Custom Symbol",
    chkCluster: "Enable Clustering",
    defineClusterSymbol: "Cluster Symbol",
    defineThemeClusterSymbol: "Cluster Symbol from Theme",
    rdoEsri: "Esri Symbol",
    rdoLayerIcon: "Use Symbol as Icon",
    rdoCustomIcon: "Upload Custom Icon",
    editCustomSymbol: "Edit Custom Symbol",
    editCustomIcon: "Edit Custom Icon",
    chkStatic: "Load Static data as new Feature Collection"
  },
  "ar": false,
  "cs": false,
  "da": false,
  "de": false,
  "es": false,
  "et": false,
  "fi": false,
  "fr": false,
  "he": false,
  "it": false,
  "ja": false,
  "ko": false,
  "lt": false,
  "lv": false,
  "nb": false,
  "nl": false,
  "pl": false,
  "pt-BR": false,
  "pt-PT": false,
  "ro": false,
  "ru": false,
  "sv": false,
  "th": false,
  "tr": false,
  "zh-cn": false
});
